import assert from 'node:assert/strict';
import { test } from 'node:test';
import { once } from 'node:events';
import { mkdtemp, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import { generateApp } from '../packages/create-tilcayo-app/dist/index.js';
import { User } from '../packages/auth/dist/models/User.js';
import { createAccessToken } from '../packages/auth/dist/tokens.js';
import { resolveConfig } from '../packages/auth/dist/types.js';
import { createApp } from '../packages/core/dist/index.js';

test('generated catalog and orders protect reads/writes, filter categories and validate saved data', async t => {
  const repo = fileURLToPath(new URL('../', import.meta.url));
  const parent = await mkdtemp(path.join(repo, '.admin-products-test-'));
  t.after(() => rm(parent, { recursive: true, force: true }));
  const root = await generateApp({ name: 'catalog', type: 'fullstack', auth: true, admin: true, install: false, packageManager: 'npm' }, parent);
  const compiler = path.join(path.dirname(createRequire(import.meta.url).resolve('typescript/package.json')), 'bin/tsc');
  execFileSync(process.execPath, [compiler, '-p', path.join(root, 'api')], { encoding: 'utf8' });
  const previous = { access: process.env.AUTH_ACCESS_SECRET, refresh: process.env.AUTH_REFRESH_SECRET };
  process.env.AUTH_ACCESS_SECRET = 'a'.repeat(64);
  process.env.AUTH_REFRESH_SECRET = 'b'.repeat(64);
  t.after(() => {
    for (const [key, value] of [['AUTH_ACCESS_SECRET', previous.access], ['AUTH_REFRESH_SECRET', previous.refresh]]) {
      if (value === undefined) delete process.env[key]; else process.env[key] = value;
    }
  });
  const load = name => import(pathToFileURL(path.join(root, 'api/dist', name)).href);
  const { Product } = await load('models/Product.js');
  const { default: routes } = await load('routes/admin-products.routes.js');
  const { default: ordersRoutes } = await load('routes/admin-orders.routes.js');
  const { Order } = await load('models/Order.js');
  const id = '1234567890abcdef12345678';
  const administrator = new User.raw({ _id: id, name: 'Admin', email: 'admin@example.test', roles: [] });
  t.mock.method(User, 'find', async () => administrator);
  const input = { name: 'Desk lamp', sku: 'LAMP-1', category: 'Lighting', price: 2500, currency: 'KES', stock: 3, status: 'active' };
  const record = new Product.raw({ _id: id, ...input });
  const list = t.mock.method(Product, 'paginate', async () => ({ items: [record], pagination: { page: 1, perPage: 10, total: 1, lastPage: 1, hasNextPage: false, hasPreviousPage: false } }));
  t.mock.method(Product, 'count', async () => 1);
  const create = t.mock.method(Product, 'create', async data => new Product.raw({ _id: id, ...data }));
  t.mock.method(Product, 'findOrFail', async () => record);
  t.mock.method(Product, 'firstOrFail', async filter => { assert.equal(filter.sku, input.sku); return record; });
  t.mock.method(Product.raw, 'aggregate', async () => [{ name: 'Lighting', totalProducts: 1, activeProducts: 1, stock: 3 }]);
  t.mock.method(Product, 'update', async (_id, data) => new Product.raw({ _id: id, ...data }));
  const orderRecord = { _id: id, productName: input.name, sku: input.sku, customerEmail: 'customer@example.test', quantity: 2, currency: 'KES', total: 5000, status: 'pending' };
  t.mock.method(Order, 'paginate', async () => ({ items: [orderRecord], pagination: { page: 1, perPage: 10, total: 1, lastPage: 1 } }));
  t.mock.method(Order, 'count', async () => 1);
  t.mock.method(Order, 'create', async fields => ({ _id: id, ...fields }));
  t.mock.method(Order, 'findOrFail', async () => orderRecord);
  t.mock.method(Order, 'update', async (_id, fields) => ({ ...orderRecord, ...fields }));
  const server = createApp().routes(routes).routes(ordersRoutes).listen(0);
  await once(server, 'listening');
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api/admin/products`;
  const ordersBase = `http://127.0.0.1:${server.address().port}/api/admin/orders`;
  const config = resolveConfig({ accessTokenSecret: process.env.AUTH_ACCESS_SECRET, refreshTokenSecret: process.env.AUTH_REFRESH_SECRET });
  const headers = { Authorization: `Bearer ${await createAccessToken(id, config)}`, 'Content-Type': 'application/json' };
  assert.equal((await fetch(base)).status, 401);
  assert.equal((await fetch(ordersBase)).status, 401);
  assert.equal((await fetch(base, { headers })).status, 403);
  assert.equal((await fetch(ordersBase, { headers })).status, 403);
  assert.equal((await fetch(base, { headers, method: 'POST', body: JSON.stringify(input) })).status, 403);
  assert.equal(create.mock.callCount(), 0);
  administrator.roles = ['admin'];
  const categories = await fetch(base + '/categories', { headers });
  assert.equal(categories.status, 200);
  assert.deepEqual((await categories.json()).data, [{ name: 'Lighting', totalProducts: 1, activeProducts: 1, stock: 3 }]);
  const categoryResponse = await fetch(base + '?category=Lighting', { headers });
  assert.equal(categoryResponse.status, 200);
  assert.equal(list.mock.calls[0].arguments[1].filter.category, 'Lighting');
  const response = await fetch(base + '?search=Lamp%2B&status=active&stock=low', { headers });
  assert.equal(response.status, 200);
  assert.equal(response.headers.get('Cache-Control'), 'no-store');
  const result = await response.json();
  assert.equal(result.data.items[0].sku, 'LAMP-1');
  assert.deepEqual(result.data.stats, { totalProducts: 1, activeProducts: 1, lowStock: 1, outOfStock: 1 });
  const filter = list.mock.calls[1].arguments[1].filter;
  assert.equal(filter.status, 'active');
  assert.deepEqual(filter.stock, { $gt: 0, $lte: 5 });
  assert.equal(filter.$or[0].name.$regex, 'Lamp\\+');
  const saved = await fetch(base, { headers, method: 'POST', body: JSON.stringify(input) });
  assert.equal(saved.status, 200);
  assert.equal((await saved.json()).data.price, 2500);
  const updated = await fetch(base + '/' + id, { headers, method: 'PUT', body: JSON.stringify({ ...input, status: 'archived', stock: 0 }) });
  assert.equal(updated.status, 200);
  assert.equal((await updated.json()).data.status, 'archived');
  const orderInput = { productSku: input.sku, customerEmail: 'customer@example.test', quantity: 3 };
  const newOrder = await fetch(ordersBase, { headers, method: 'POST', body: JSON.stringify(orderInput) });
  assert.equal(newOrder.status, 200);
  const orderData = (await newOrder.json()).data;
  assert.equal(orderData.total, 7500);
  assert.equal(orderData.unitPrice, 2500);
  assert.equal(orderData.currency, 'KES');
  assert.equal(orderData.status, 'pending');
  const orderList = await fetch(ordersBase + '?status=pending', { headers });
  assert.equal(orderList.status, 200);
  assert.equal((await orderList.json()).data.stats.pending, 1);
  const fulfilled = await fetch(ordersBase + '/' + id, { headers, method: 'PUT', body: JSON.stringify({ status: 'fulfilled' }) });
  assert.equal(fulfilled.status, 200);
  assert.equal((await fulfilled.json()).data.status, 'fulfilled');
  for (const change of [{ quantity: 0 }, { quantity: 1.5 }, { customerEmail: 'invalid' }, { total: 1 }, { status: 'fulfilled' }]) {
    assert.equal((await fetch(ordersBase, { headers, method: 'POST', body: JSON.stringify({ ...orderInput, ...change }) })).status, 422);
  }
  assert.equal((await fetch(ordersBase + '/' + id, { headers, method: 'PUT', body: JSON.stringify({ status: 'paid' }) })).status, 422);
  for (const change of [{ stock: -1 }, { stock: 1.5 }, { price: -1 }, { status: 'bad' }, { currency: 'bad' }, { name: '' }, { $set: { stock: 99 } }]) {
    assert.equal((await fetch(base, { headers, method: 'POST', body: JSON.stringify({ ...input, ...change }) })).status, 422);
  }
  assert.equal((await fetch(base + '/bad', { headers, method: 'PUT', body: JSON.stringify(input) })).status, 422);
  assert.equal((await fetch(base + '?stock=bad', { headers })).status, 422);
  const { seedAdminDemo } = await load('scripts/seed-admin-demo.js');
  t.mock.method(Product.raw, 'exists', async () => null);
  t.mock.method(Order.raw, 'exists', async () => null);
  const demoProducts = new Map();
  const demoOrders = new Map();
  const storeInsert = records => async (filter, update, options) => {
    assert.equal(filter.demoBatch, 'tilcayo-admin-demo-v1');
    assert.equal(options.timestamps, false);
    assert.ok(update.$setOnInsert);
    const key = String(filter._id);
    if (!records.has(key)) records.set(key, { _id: key, ...update.$setOnInsert });
  };
  const demoWrites = t.mock.method(Product.raw, 'updateOne', storeInsert(demoProducts));
  t.mock.method(Order.raw, 'updateOne', storeInsert(demoOrders));
  await seedAdminDemo();
  assert.equal(demoProducts.size, 8);
  assert.equal(demoOrders.size, 6);
  assert.equal(new Set([...demoProducts.values()].map(product => product.category)).size, 3);
  assert.ok([...demoProducts.values()].every(product => product.imageUrl.startsWith('https://')));
  const firstDemo = demoProducts.values().next().value;
  firstDemo.price = 9999;
  await seedAdminDemo();
  assert.equal(demoProducts.size, 8);
  assert.equal(demoOrders.size, 6);
  assert.equal(firstDemo.price, 9999);
  const writesBefore = demoWrites.mock.callCount();
  t.mock.method(Product.raw, 'exists', async () => ({ _id: id }));
  await assert.rejects(seedAdminDemo(), /conflict/);
  assert.equal(demoWrites.mock.callCount(), writesBefore);
  t.mock.method(Product, 'create', async () => { throw Object.assign(new Error('private database details'), { code: 11000 }); });
  const duplicate = await fetch(base, { headers, method: 'POST', body: JSON.stringify(input) });
  assert.equal(duplicate.status, 409);
  assert.ok(!JSON.stringify(await duplicate.json()).includes('private'));
});
